# Generated by Django 3.2.8 on 2021-10-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_number_rec_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carplatenumber',
            name='contour',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carplatenumber',
            name='detected_each_char',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carplatenumber',
            name='detected_plate_img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
