# Generated by Django 3.2.8 on 2021-10-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plate_number_rec_app', '0002_auto_20211017_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carplatenumber',
            old_name='car_plate_img',
            new_name='car_img',
        ),
    ]
